---
title: "First Entrance 2021"
#description: |
#  A new article created using the Distill #format.
#author:
#  - name: Nora Jones 
#    url: https://example.com/norajones
#    affiliation: Spacely Sprockets
#    affiliation_url: #https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
### The 2021 First Entrance Results

The University of Liberia has released official results for the May 1, 2021, 1st Entrance and Placement Examination administered in seven counties across the country.
The centers included Zwedru, Grand Gedeh County;
Ganta, Nimba County; Tubmanburg, Bomi County; Voinjama, Lofa County; Buchanan, Grand Bassa County; Sinje, Grand Cape Mount County and Montserrado County.
Here are links to the comprehensive results for each category. Please note that this release does not include the Law School result as it is scheduled to be released at a later date. 

### Links For The Results

<html>
  <head>
    <title>Title of the document</title>
    <style>
      .button {
        display: inline-block;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        color: #ffffff;
        background-color: #7aa8b7;
        border-radius: 6px;
        outline: none;
        transition: 0.3s;
      }
      .button:hover {
        background-color: #c2c7c7;
      }
    </style>
  </head>
  <body>
    <a class="button" href="https://l.facebook.com/l.php?u=https%3A%2F%2Fsyr.us%2Fej1%3Ffbclid%3DIwAR2PvXY0JcJvlrX-nO8EkS-hNtxE1517sGcD6UdsQk0SOD9GA3xF1F5bFnI&h=AT2-SjvHXX1UoNHNHVuQURJJ1ueIt_fW_zEse_SwL-B2Q-sfuntKohcGHfYEVYeyWg_uNPCFWkgqDQIkMGI2MDmhTmLqYJK5CmFhQngdiFx8PdIq0bMuIpdD94TPsdeGwhLA9Q4MjQ&__tn__=-UK-R&c[0]=AT0VUOUsF3QCaN0Jnb0vErqZpWGDyML6VE-wJEdRXiNj__MVonSVPWD5KOu8xgj3wKTVT798IvZXk7voayg7tOt6xyzBzExkLH-c_DnLo3YLdgohtX4TGfKzQ2kCLH96bSnfK1tSRd1-44dTs87AwJoSagdyhA">Click Here For The Graduate Schools Results</a>
  </body>
</html>



### The  Medical School

<html>
  <head>
    <title>Title of the document</title>
    <style>
      .button {
        display: inline-block;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        color: #ffffff;
        background-color: #7aa8b7;
        border-radius: 6px;
        outline: none;
        transition: 0.3s;
      }
      .button:hover {
        background-color: #c2c7c7;
      }
    </style>
  </head>
  <body>
    <a class="button" href="https://l.facebook.com/l.php?u=https%3A%2F%2Fsyr.us%2F9vE%3Ffbclid%3DIwAR2LftqJgSGrOCdu0XEp6daq6TpXQ2uzx3KWB32fsJX1ki5Xy_Ep5PtLlgQ&h=AT08Cs-7xsJLBA286m3Y7y-pL88Pw_OhDmw2aBqKnDwXEAG9-6y4EpA2IPsmWfnQlsmXsfsLwVw2I0Y_dohfsPNVcvVifT8am8BpS59Vqo61Y0rsIRxO9UsWijdhYtoF4yOaFI3lrQ&__tn__=-UK-R&c[0]=AT0VUOUsF3QCaN0Jnb0vErqZpWGDyML6VE-wJEdRXiNj__MVonSVPWD5KOu8xgj3wKTVT798IvZXk7voayg7tOt6xyzBzExkLH-c_DnLo3YLdgohtX4TGfKzQ2kCLH96bSnfK1tSRd1-44dTs87AwJoSagdyhA">Click Here For The Medical School Results</a>
  </body>
</html>


### The  School of Pharmacy 


<html>
  <head>
    <title>Title of the document</title>
    <style>
      .button {
        display: inline-block;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        color: #ffffff;
        background-color: #7aa8b7;
        border-radius: 6px;
        outline: none;
        transition: 0.3s;
      }
      .button:hover {
        background-color: #c2c7c7;
      }
    </style>
  </head>
  <body>
    <a class="button" href="https://l.facebook.com/l.php?u=https%3A%2F%2Fsyr.us%2F6hb%3Ffbclid%3DIwAR1K-fT42NKYxyFMU2krTqPH_mz4L-1k-hnKhBHn3m1RQEJWhfJvs029V4E&h=AT1GqmUAm5sw-P1OWAXS8l_aL4mx0_2W7buT23c4TeF-Oys0tJB8_nt-qlOBmNLogAjRlFfoUHB11g3ON4KwTztABGrcNuLbCmUE-uoWDQdqzuyOAceoExOCp9bKY67PSfU5f1d8Rw&__tn__=-UK-R&c[0]=AT0VUOUsF3QCaN0Jnb0vErqZpWGDyML6VE-wJEdRXiNj__MVonSVPWD5KOu8xgj3wKTVT798IvZXk7voayg7tOt6xyzBzExkLH-c_DnLo3YLdgohtX4TGfKzQ2kCLH96bSnfK1tSRd1-44dTs87AwJoSagdyhA">Click Here For School of Pharmacy Results</a>
  </body>
</html>

### The Undergraduate Colleges

<html>
  <head>
    <title>Title of the document</title>
    <style>
      .button {
        display: inline-block;
        padding-left:10px;
        padding-right:10px;
        text-align: center;
        text-decoration: none;
        color: #ffffff;
        background-color: #7aa8b7;
        border-radius: 6px;
        outline: none;
        transition: 0.3s;
      }
      .button:hover {
        background-color: #c2c7c7;
      }
      .button {width: 350px;}
      
    </style>
  </head>
  <body>
    <a class="button" href="https://l.facebook.com/l.php?u=https%3A%2F%2Fsyr.us%2Fq2C%3Ffbclid%3DIwAR30PQlahZdZdG1mfkdkJyfuZvUWTyBvPvsqBvC2BEfGmTTB-eU7yOH7n9o&h=AT0lNrBEtbO-GYQbfNgSQCjPyZ-HcbKShWpHkiW7KsmcSC65dQlfAOe7EGnezrtKK48n5TZidUcMqBOlzSVHoC5CQvk1ovEQX9U5yzXiQNA7a1h_mFsvnNLhJAFHWKJrFQlIoURLNg&__tn__=-UK-R&c[0]=AT0VUOUsF3QCaN0Jnb0vErqZpWGDyML6VE-wJEdRXiNj__MVonSVPWD5KOu8xgj3wKTVT798IvZXk7voayg7tOt6xyzBzExkLH-c_DnLo3YLdgohtX4TGfKzQ2kCLH96bSnfK1tSRd1-44dTs87AwJoSagdyhA">Click Here For The Undergraduate Results</a>
  </body>
</html>



### Results Video Presentation 

<iframe src="https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fweb.facebook.com%2Ftheuniversityofliberia%2Fvideos%2F206757904627698%2F&show_text=false&width=560&t=0" width="560" height="314" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe>
