---
title: "Second Entrance 2022"
#description: |
#author:
#  - name: Nora Jones 
#    url: https://example.com/norajones
#    affiliation: Spacely Sprockets
#    affiliation_url: #https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### The 2022 Second Entrance Results

The University of Liberia has released the results for its Second Entrance and Placement Exam administered in November 2022, with a record 2,358 female candidates making successful passes for the Undergraduate category.    

This number constitutes 49.53 percent of the 4,761 candidates who passed the exam.
The 2022 results show that 2,403 male candidates passed the exam (constituting 50.07%), compared to 2,358 females who passed.
Unlike previous years, the latest statistics indicate a narrowed gap between male and female candidates who sat and passed the UL Entrance.    

Releasing the results Wednesday, February 1, 2023, on the Capitol Hill campus, UL Center for Testing and Evaluation (CTE) Executive Director Mr. Moses Hinneh said a total of 9,785 candidates registered for the entrance for the Undergraduate and the College of General Studies levels.

Of this number, Mr. Hinneh said 9,602 or 98% candidates wrote the exams, one candidate (1 or 0.01%) was disqualified for cheating, while 183 or 2% candidates were absent.


Mr. Hinneh detailed that of the 9,602 candidates whose grades were analysed, 3,241, or 33.76% candidates passed regularly, 1,520, or 15.83% of the candidates passed provisionally, while 4,840 or 50.41% of candidates were unsuccessful.


This also means that 4,761 or 49.59% of Undergraduate candidates made either a Regular Pass or a Provisional Pass and are therefore eligible to apply for admission according to Mr. Hinneh.

For the Graduate School, he said a total of 276 candidates wrote the Aptitude Test. Of this number, Mr. Hinneh reported that 104, or 37.68% of the candidates were successful, while 172 or 62.32% candidates were unsuccessful.

34  (32.69%) of the total candidates who passed the Graduate School Aptitude Test are females, while 70 (67.31%) are males.
The 2022 Second Entrance results further indicate that 2,098 of the total number of candidates who passed, constituting 44.07% (including females), will be admitted to the sciences.


Compared to 2021, the highest number of candidates (1,966 which constituted 35.49%) were admitted in the A. Romeo Horton College of Business and Public Administration.

The results also record at least thirty-four female candidates making successful passes out of the 104 candidates who wrote the Graduate School Aptitude Test. 
That number constitutes thirty-four percent (34%) of the total number.    


The results further state that of 154 candidates who registered for the Law School Aptitude Test, three were absent.
Of the 151 candidates who wrote the Law School Aptitude Test, the results show that 44 (29.14%) candidates were successful, and 107 (70.86%) were unsuccessful.    

 Thirty-four (77.27%) of the candidates were males, while ten (22.73%) were females. The CTE results also show that High School Graduates recorded the highest number of successful candidates (4,672), followed by current twelve graders, 62, and 22 candidates from other universities.    
 
The overall results indicate that candidates from faith-based schools recorded the highest number of successful candidates, amounting to 1,989 (41.78%) of the total number.    


Of the Fifteen counties, Lofa County, recorded the highest number of successful candidates with a total of 1,047 (21.99%) of the total number. In 2021, Lofa also recorded the highest number, with a total of 1,194 (21.56%) successful candidates.    

While the results were being released, Prof. Dr. Julius Julukon Sarwolo Nelson, Jr., said as President of the University of Liberia, the high participation rate in UL’s entrance exam process brings him great joy as well as strong reminders of the challenges at hand.    

President Nelson said the 9,602 candidates who sat the Second Entrance joined the over 12,000 candidates who sat the First Entrance to give UL more than 21,000 total candidates who participated in the 2022 entrance exam cycle.    

The UL President said this trend of heightened interest in the University’s enrollment processes point to changes in the higher education sub-sector which have made tertiary education more affordable and attainable without compromising quality.    

“This is why as managers and administrators of this premier public higher education institution, we are always pleased to see the continuous demonstration of desires by Liberians of various works of life to acquire higher education and build their capacities here at the University of Liberia (Lux In Tenebris),” said President Nelson.    

Dr. Nelson explained that the current enrollment is more than 21,000, of whom over 2,000 will be leaving UL during the 103rd Commencement Convocation in May/June this year.    

“Though we are extremely excited as always, to welcome more and more new intakes, we must also ensure that other targeted variables are attained. It is our responsibility to attract the best and brightest students through these processes to ensure that the quality and standard of our brand remain high,” he added.    

He continued that UL administrators are cognizant of the changing faculty-student ratio, and this is why faculty and staff development is a high priority.    
The UL President stated that there is also a glaringly urgent need for infrastructure upgrade, maintenance, and construction of new facilities not just to respond to the increasing demand for affordable higher education in Liberia but also to deal with legacy issues on UL campuses.    



<html>
  <head>
    <title>Title of the document</title>
    <style>
      .button {
        display: inline-block;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        color: #ffffff;
        background-color: #7aa8b7;
        border-radius: 6px;
        outline: none;
        transition: 0.3s;
      }
      .button:hover {
        background-color: #c2c7c7;
      }
    </style>
  </head>
  <body>
    <a class="button" href="https://l.facebook.com/l.php?u=https%3A%2F%2Frstudio-pubs-static.s3.amazonaws.com%2F997522_0f5730b119e645c9a3db087df413c799.html%3Ffbclid%3DIwAR0KHNrEv-rQOAsWC4UN7UapoBeLulaJ2zU_XmWSd5386oGtS5MbTtrZhDw%23exam-results&h=AT1I28J5x1A0p-qeN7w3aDJGh_q5SlL7pCRees_3lDq8DpUR0vwF_BcJFNoZRi9H0lq8VM4bhdMCQ-SPMuvsbFocl8YspYGDPnjelW4ksITuxvJXZFIoVNdsizXoL4I_77ZJfpe4FQ&__tn__=-UK-R&c[0]=AT1L_a6u6RqAkRxcRgGuLs7PuQxjaTq5dg1tnHTu2BE3GzkLnL0oG3gGlDp3phXQ5muDanpPimzI5PqIyg2wvZm-x1MCBhyX6zhxQfxmleSqljg7J_n0L3TQHJ769fxYmKkdFPK5uqDhWA80kIBvUtRTE-iEHbIQQttV2uI5UISgPfAJ2csi-aV25SUTPZGzkrtGoGE-_Y-Z">Click Here For The 2022 Second Entrance Results</a>
  </body>
</html>


### Results Video Presentation 
<iframe width="560" height="315" src="https://www.youtube.com/embed/lHLNpWdpouw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>